name: xWhitelist
main: org.eldrygo.XWhitelist
version: 1.2.0
api-version: 1.13
softdepend: [PlaceholderAPI]
commands:
  xwhitelist:
    description: "Whitelist commands"
    aliases:
        - xwl
    subcommands:
      enable:
        description: "Enable the whitelist."
      disable:
        description: "Disable the whitelist."
      add:
        description: "Add a player to the whitelist."
      remove:
        description: "Remove a player from the whitelist."
      list:
        description: "List the players in the whitelist."
      cleanup:
        description: "Clean the whitelist."
      reload:
        description: "Reload the configuration."
      help:
        description: "Show the command list."
      info:
        description: "Display plugin information."
      maintenance:
        description: "Sub command to all the maintenance whitelist management commands."
        subcommands:
          enable:
            description: "Enable the maintenance whitelist."
          disable:
            description: "Disable the maintenance whitelist."
          add:
            description: "Add a player to the maintenance whitelist."
          remove:
            description: "Remove a player from the maintenance whitelist."
          list:
            description: "List the players in the maintenance whitelist."
          cleanup:
            description: "Clean the maintenance whitelist."
permissions:
  xwhitelist.admin:
    description: "Access to all plugin commands."
    default: false
  xwhitelist.whitelist:
    description: "Access to the whitelist commands."
    default: false
    children:
      xwhitelist.whitelist.enable: true
      xwhitelist.whitelist.disable: true
      xwhitelist.whitelist.add: true
      xwhitelist.whitelist.remove: true
      xwhitelist.whitelist.list: true
      xwhitelist.whitelist.cleanup: true
  xwhitelist.plugin:
    description: "Access to the plugin commands."
    default: false
    children:
      xwhitelist.plugin.reload: true
      xwhitelist.plugin.help: true
      xwhitelist.plugin.info: true
  xwhitelist.maintenance:
    description: "Access to the maintenance whitelist commands."
    default: false
    children:
      xwhitelist.maintenance.enable: true
      xwhitelist.maintenance.disable: true
      xwhitelist.maintenance.add: true
      xwhitelist.maintenance.remove: true
      xwhitelist.maintenance.list: true
      xwhitelist.maintenance.cleanup: true